# Generated by Django 2.1.5 on 2022-03-09 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 16, 20, 17, 93877, tzinfo=utc)),
        ),
    ]
