# Generated by Django 4.0.3 on 2022-05-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='icon_url',
            field=models.TextField(null=True, verbose_name='Путь к иконке'),
        ),
    ]
