# Generated by Django 4.0.2 on 2022-05-07 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tests', '0002_test_icon_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronologyExercise',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.exercise')),
            ],
            bases=('tests.exercise',),
        ),
        migrations.AddField(
            model_name='test',
            name='date_published',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='VariantChronologyExercise',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.exercise')),
                ('name', models.TextField()),
                ('order', models.IntegerField(verbose_name='Порядковый номер')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.chronologyexercise')),
            ],
            bases=('tests.exercise',),
        ),
    ]
