# Generated by Django 4.0.3 on 2022-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_chronologyexercise_exercise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronologyexercise',
            name='exercise_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='matchexercise',
            name='exercise_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
