# Generated by Django 4.0.2 on 2022-05-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_chronologyexercise_test_date_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='count_of_passes',
            field=models.IntegerField(default=0),
        ),
    ]
