# Generated by Django 4.0.3 on 2022-06-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_chronologyexercise_exercise_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexercise',
            name='project_exercise_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='projecttaskelement_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projecttaskelement'),
        ),
    ]
