# Generated by Django 4.0.3 on 2022-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_projectexercise_project_exercise_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectexercise',
            name='project_exercise_id',
        ),
        migrations.AddField(
            model_name='projectexercise',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
