# Generated by Django 4.0.2 on 2022-05-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_test_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='icon',
            field=models.ImageField(upload_to='tests/uploaded_icons'),
        ),
    ]
