# Generated by Django 4.0.3 on 2022-06-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_projectexercise_project_exercise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronologyexercise',
            name='exercise_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchexercise',
            name='exercise_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projecttaskelement',
            name='element_id',
            field=models.AutoField(db_column='element_id', primary_key=True, serialize=False, unique=True),
        ),
    ]
