# Generated by Django 4.0.2 on 2022-05-10 20:25

from django.db import migrations, models
import tests.models.test


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_test_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='icon',
            field=models.ImageField(upload_to=tests.models.test.user_media_path),
        ),
    ]
