# Generated by Django 4.0.2 on 2022-05-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_test_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_of_tasks',
            field=models.IntegerField(default=0, verbose_name='Количество заданий'),
        ),
    ]
