# Generated by Django 4.0.2 on 2022-06-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerExercise',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Название упражнения')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputExercise',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Название упражнения')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('prepared_answer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadioExercise',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Название упражнения')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatementsExercise',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Название упражнения')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='projecttaskelement',
            name='element_type',
            field=models.IntegerField(choices=[(0, 'Упражнение'), (1, 'Заголовок'), (2, 'Изображение'), (3, 'Карты (Yandex Maps)')], default=0, verbose_name='Тип элемента'),
        ),
        migrations.CreateModel(
            name='ProjectAnswerExercise',
            fields=[
                ('projectexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectexercise')),
                ('answerexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.answerexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.answerexercise', 'tests.projectexercise'),
        ),
        migrations.CreateModel(
            name='ProjectInputExercise',
            fields=[
                ('projectexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectexercise')),
                ('inputexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.inputexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.inputexercise', 'tests.projectexercise'),
        ),
        migrations.CreateModel(
            name='ProjectRadioExercise',
            fields=[
                ('projectexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectexercise')),
                ('radioexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.radioexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.radioexercise', 'tests.projectexercise'),
        ),
        migrations.CreateModel(
            name='ProjectStatementsExercise',
            fields=[
                ('projectexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectexercise')),
                ('statementsexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.statementsexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.statementsexercise', 'tests.projectexercise'),
        ),
        migrations.CreateModel(
            name='VariantStatementsExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.statementsexercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantRadioExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.radioexercise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
