# Generated by Django 4.0.2 on 2022-05-11 11:10

from django.db import migrations, models
import tests.models.test


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_test_number_of_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='icon',
            field=models.ImageField(default='icon.ico', upload_to=tests.models.test.user_media_path),
        ),
    ]
