# Generated by Django 4.0.2 on 2022-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_answerexercise_inputexercise_radioexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttaskelement',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
