# Generated by Django 4.0.2 on 2022-05-14 14:04

from django.db import migrations, models
import tests.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_testcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='icon.ico', upload_to=tests.models.user.user_media_path),
        ),
    ]
