# Generated by Django 4.0.2 on 2022-06-11 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_projecttask_description_md_task_description_md_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesExercise',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Название упражнения')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Заголовок')),
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='exercise_type',
            field=models.IntegerField(choices=[(0, 'Ответить на вопрос'), (1, 'Написать развёрнутый ответ'), (2, 'Отметить верные утверждения'), (3, 'Выбрать одно верное утверждение'), (4, 'Соотнести что-то с чем-то'), (5, 'Составить правильный порядок карточек'), (5, 'Выбери подходящие изображения')], default=0),
        ),
        migrations.CreateModel(
            name='ProjectImagesExercise',
            fields=[
                ('projectexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectexercise')),
                ('imagesexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.imagesexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.imagesexercise', 'tests.projectexercise'),
        ),
        migrations.CreateModel(
            name='PictureImagesExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='')),
                ('checked', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.imagesexercise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
