# Generated by Django 4.0.2 on 2022-05-14 14:05

from django.db import migrations, models
import tests.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to=tests.models.user.user_media_path),
        ),
    ]
