# Generated by Django 4.0.2 on 2022-05-16 18:38

from django.db import migrations, models
import tests.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfact',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to=tests.models.user.user_media_path, verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
    ]
