# Generated by Django 4.0.2 on 2022-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_imagesexercise_alter_projectexercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexercise',
            name='exercise_type',
            field=models.IntegerField(choices=[(0, 'Ответить на вопрос'), (1, 'Написать развёрнутый ответ'), (2, 'Отметить верные утверждения'), (3, 'Выбрать одно верное утверждение'), (4, 'Соотнести что-то с чем-то'), (5, 'Составить правильный порядок карточек'), (6, 'Выбери подходящие изображения')], default=0),
        ),
    ]
