# Generated by Django 4.0.2 on 2022-05-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_testfact_completed_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
