# Generated by Django 4.0.2 on 2022-05-17 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcomment',
            name='date_published',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='testcomment',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
