# Generated by Django 4.0.2 on 2022-06-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_basedocumentelement_basequoteelement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseDocumentElement',
        ),
        migrations.DeleteModel(
            name='BaseQuoteElement',
        ),
        migrations.DeleteModel(
            name='BaseYandexMapsElement',
        ),
    ]
