# Generated by Django 4.0.2 on 2022-05-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_testcomment_date_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcomment',
            name='published',
        ),
    ]
