# Generated by Django 4.0.2 on 2022-05-17 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_remove_testcomment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomment',
            name='date_published',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
