# Generated by Django 4.0.2 on 2022-06-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_delete_basedocumentelement_delete_basequoteelement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentElement',
            fields=[
                ('type', models.IntegerField(choices=[(0, 'Заголовок'), (1, 'Изображение'), (2, 'Цитата'), (3, 'Документ'), (4, 'Карты (Yandex Maps)')], default=0, verbose_name='Тип статичного элемента')),
                ('static_element_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Содержание документа')),
                ('name', models.CharField(max_length=100, verbose_name='Название документа')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PictureElement',
            fields=[
                ('type', models.IntegerField(choices=[(0, 'Заголовок'), (1, 'Изображение'), (2, 'Цитата'), (3, 'Документ'), (4, 'Карты (Yandex Maps)')], default=0, verbose_name='Тип статичного элемента')),
                ('static_element_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='project/static_pictures', verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteElement',
            fields=[
                ('type', models.IntegerField(choices=[(0, 'Заголовок'), (1, 'Изображение'), (2, 'Цитата'), (3, 'Документ'), (4, 'Карты (Yandex Maps)')], default=0, verbose_name='Тип статичного элемента')),
                ('static_element_id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.TextField(default='Цитата - очень важный элемент для теста', verbose_name='Цитата')),
                ('author', models.CharField(max_length=100, verbose_name='Автор цитаты')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YandexMapsElement',
            fields=[
                ('type', models.IntegerField(choices=[(0, 'Заголовок'), (1, 'Изображение'), (2, 'Цитата'), (3, 'Документ'), (4, 'Карты (Yandex Maps)')], default=0, verbose_name='Тип статичного элемента')),
                ('static_element_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentElement',
            fields=[
                ('projectstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectstaticelement')),
                ('documentelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.documentelement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.documentelement', 'tests.projectstaticelement'),
        ),
        migrations.CreateModel(
            name='ProjectPictureElement',
            fields=[
                ('projectstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectstaticelement')),
                ('pictureelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.pictureelement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.pictureelement', 'tests.projectstaticelement'),
        ),
        migrations.CreateModel(
            name='ProjectQuoteElement',
            fields=[
                ('projectstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectstaticelement')),
                ('quoteelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.quoteelement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.quoteelement', 'tests.projectstaticelement'),
        ),
        migrations.CreateModel(
            name='ProjectYandexMapsElement',
            fields=[
                ('projectstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.projectstaticelement')),
                ('yandexmapselement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.yandexmapselement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.yandexmapselement', 'tests.projectstaticelement'),
        ),
    ]
