# Generated by Django 4.0.2 on 2022-05-17 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_alter_testcomment_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcomment',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
