# Generated by Django 4.0.2 on 2022-06-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_alter_pictureelement_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yandexmapselement',
            name='url',
        ),
        migrations.AddField(
            model_name='yandexmapselement',
            name='frame',
            field=models.TextField(default='', verbose_name='iframe'),
            preserve_default=False,
        ),
    ]
