# Generated by Django 4.0.2 on 2022-06-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_keymatchlistexercise_matchlistexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.project'),
            preserve_default=False,
        ),
    ]
