# Generated by Django 4.0.2 on 2022-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_test_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='description_md',
        ),
        migrations.RemoveField(
            model_name='test',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='number_of_tasks',
        ),
    ]
