# Generated by Django 4.0.2 on 2022-05-22 05:47

from django.db import migrations, models
import tests.models.test


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='New Task', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='icon',
            field=models.ImageField(default='test_icon.png', upload_to=tests.models.test.user_media_path),
        ),
    ]
