# Generated by Django 4.0.2 on 2022-06-16 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_remove_test_author_remove_test_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(verbose_name='Номер задания')),
                ('title', models.TextField(default='New Task', verbose_name='Заголовок')),
                ('description_md', models.TextField(default='Объяснение задания\n=======')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.testfact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFactElement',
            fields=[
                ('element_type', models.IntegerField(choices=[(0, 'Упражнение'), (1, 'Статичный элемент')], default=0, verbose_name='Тип элемента')),
                ('element_id', models.AutoField(db_column='element_id', primary_key=True, serialize=False, unique=True)),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.taskfact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestFactExercise',
            fields=[
                ('taskfactelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.taskfactelement')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('exercise_type', models.IntegerField(choices=[(0, 'Ответить на вопрос'), (1, 'Написать развёрнутый ответ'), (2, 'Отметить верные утверждения'), (3, 'Выбрать одно верное утверждение'), (4, 'Соотнести что-то с чем-то'), (7, 'Соотнеси что-то с элементом из списка'), (5, 'Составить правильный порядок карточек'), (6, 'Выбери подходящие изображения')], default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.taskfactelement',),
        ),
        migrations.CreateModel(
            name='TestFactStaticElement',
            fields=[
                ('taskfactelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.taskfactelement')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('static_element_type', models.IntegerField(choices=[(0, 'Заголовок'), (1, 'Изображение'), (2, 'Цитата'), (3, 'Документ'), (4, 'Карты (Yandex Maps)')], default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.taskfactelement',),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
