# Generated by Django 4.0.2 on 2022-05-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_task_name_alter_test_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='Title of this task', verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
