# Generated by Django 4.0.2 on 2022-06-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_taskfact_taskfactelement_testfactexercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactAnswerExercise',
            fields=[
                ('testfactexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactexercise')),
                ('answerexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.answerexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.answerexercise', 'tests.testfactexercise'),
        ),
        migrations.CreateModel(
            name='FactChronologyExercise',
            fields=[
                ('testfactexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactexercise')),
                ('chronologyexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.chronologyexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.chronologyexercise', 'tests.testfactexercise'),
        ),
        migrations.CreateModel(
            name='FactDocumentElement',
            fields=[
                ('testfactstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactstaticelement')),
                ('documentelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.documentelement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.documentelement', 'tests.testfactstaticelement'),
        ),
        migrations.CreateModel(
            name='FactImagesExercise',
            fields=[
                ('testfactexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactexercise')),
                ('imagesexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.imagesexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.imagesexercise', 'tests.testfactexercise'),
        ),
        migrations.CreateModel(
            name='FactInputExercise',
            fields=[
                ('testfactexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactexercise')),
                ('inputexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.inputexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.inputexercise', 'tests.testfactexercise'),
        ),
        migrations.CreateModel(
            name='FactMatchExercise',
            fields=[
                ('testfactexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactexercise')),
                ('matchexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.matchexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.matchexercise', 'tests.testfactexercise'),
        ),
        migrations.CreateModel(
            name='FactMatchListExercise',
            fields=[
                ('testfactexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactexercise')),
                ('matchlistexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.matchlistexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.matchlistexercise', 'tests.testfactexercise'),
        ),
        migrations.CreateModel(
            name='FactPictureElement',
            fields=[
                ('testfactstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactstaticelement')),
                ('pictureelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.pictureelement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.pictureelement', 'tests.testfactstaticelement'),
        ),
        migrations.CreateModel(
            name='FactQuoteElement',
            fields=[
                ('testfactstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactstaticelement')),
                ('quoteelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.quoteelement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.quoteelement', 'tests.testfactstaticelement'),
        ),
        migrations.CreateModel(
            name='FactRadioExercise',
            fields=[
                ('testfactexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactexercise')),
                ('radioexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.radioexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.radioexercise', 'tests.testfactexercise'),
        ),
        migrations.CreateModel(
            name='FactStatementsExercise',
            fields=[
                ('testfactexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactexercise')),
                ('statementsexercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.statementsexercise')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.statementsexercise', 'tests.testfactexercise'),
        ),
        migrations.CreateModel(
            name='FactTitleElement',
            fields=[
                ('testfactstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactstaticelement')),
                ('titleelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.titleelement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.titleelement', 'tests.testfactstaticelement'),
        ),
        migrations.CreateModel(
            name='FactYandexMapsElement',
            fields=[
                ('testfactstaticelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.testfactstaticelement')),
                ('yandexmapselement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.yandexmapselement')),
            ],
            options={
                'abstract': False,
            },
            bases=('tests.yandexmapselement', 'tests.testfactstaticelement'),
        ),
    ]
