# Generated by Django 4.0.2 on 2022-06-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_factanswerexercise_factchronologyexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexercise',
            name='max_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskfact',
            name='max_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskfact',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testfact',
            name='max_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testfact',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testfactexercise',
            name='max_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testfactexercise',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testfactexercise',
            name='success',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='variantchronologyexercise',
            name='current_order',
            field=models.IntegerField(default=-1, verbose_name='Выбранный номер'),
        ),
    ]
