# Generated by Django 4.0.2 on 2022-05-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_user_groups_alter_user_user_permissions'),
        ('tests', '0025_task_title'),
    ]

    operations = [
    ]
