# Generated by Django 4.0.2 on 2022-05-27 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tests.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_merge_20220527_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New test', max_length=100, verbose_name='Название')),
                ('description', models.TextField(default='Description', verbose_name='Описание')),
                ('icon', models.ImageField(default='test_icon.png', upload_to=tests.models.base.user_media_path)),
                ('number_of_tasks', models.IntegerField(default=0, verbose_name='Количество заданий')),
                ('project_name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='task',
        ),
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test',
            name='count_of_passes',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.RemoveField(
            model_name='test',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='number_of_tasks',
        ),
        migrations.RemoveField(
            model_name='test',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='published',
        ),
        migrations.RemoveField(
            model_name='test',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='current_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.TextField(default='New Task', verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='testfact',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test'),
        ),
        migrations.AlterField(
            model_name='testfact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Испытуемый'),
        ),
        migrations.CreateModel(
            name='TestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New test', max_length=100, verbose_name='Название')),
                ('description', models.TextField(default='Description', verbose_name='Описание')),
                ('icon', models.ImageField(default='test_icon.png', upload_to=tests.models.base.user_media_path)),
                ('number_of_tasks', models.IntegerField(default=0, verbose_name='Количество заданий')),
                ('version', models.IntegerField()),
                ('published_at', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(verbose_name='Номер задания')),
                ('title', models.TextField(default='New Task', verbose_name='Заголовок')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'answer'), (1, 'input'), (2, 'statements'), (3, 'radio'), (4, 'match'), (5, 'chronology')], verbose_name='Тип упражнения')),
                ('title', models.TextField(null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.projecttask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
