# Generated by Django 4.0.2 on 2022-06-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_alter_taskfact_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantmatchexercise',
            name='current_column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_column', to='tests.columnmatchexercise'),
        ),
    ]
