# Generated by Django 4.0.2 on 2022-05-27 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tests.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_projecttask_author_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testversion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testversion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testversion',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='testversion',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testversion',
            name='number_of_tasks',
        ),
        migrations.AddField(
            model_name='test',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default='Description', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='test',
            name='icon',
            field=models.ImageField(default='test_icon.png', upload_to=tests.models.base.user_media_path),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='New test', max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='test',
            name='number_of_tasks',
            field=models.IntegerField(default=0, verbose_name='Количество заданий'),
        ),
    ]
