# Generated by Django 4.0.2 on 2022-05-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_remove_testversion_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testversion',
            name='number_of_tasks',
            field=models.IntegerField(default=0, verbose_name='Количество заданий'),
        ),
    ]
