# Generated by Django 4.0.2 on 2022-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_variantradioexercise_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputexercise',
            name='current_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
