# Generated by Django 4.0.2 on 2022-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_inputexercise_current_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputexercise',
            name='current_answer',
        ),
        migrations.AddField(
            model_name='factanswerexercise',
            name='current_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factinputexercise',
            name='current_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
