# Generated by Django 4.0.2 on 2022-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_remove_inputexercise_current_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureimagesexercise',
            name='current_checked',
            field=models.BooleanField(default=False),
        ),
    ]
