# Generated by Django 4.0.2 on 2022-06-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_pictureimagesexercise_current_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuematchlistexercise',
            name='key',
        ),
    ]
