# Generated by Django 4.0.2 on 2022-06-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_remove_valuematchlistexercise_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymatchlistexercise',
            name='current_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_value', to='tests.valuematchlistexercise'),
        ),
        migrations.AddField(
            model_name='keymatchlistexercise',
            name='value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='tests.valuematchlistexercise'),
            preserve_default=False,
        ),
    ]
