# Generated by Django 4.0.2 on 2022-05-28 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_alter_exercise_name_alter_exercise_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectexercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.IntegerField(choices=[(0, 'Ответить на вопрос'), (1, 'Написать развёрнутый ответ'), (2, 'Отметить верные утверждения'), (3, 'Выбрать одно верное утверждение'), (4, 'Соотнести что-то с чем-то'), (5, 'Составить правильный порядок карточек')], default=0, verbose_name='Тип упражнения'),
        ),
        migrations.AlterField(
            model_name='projectexercise',
            name='type',
            field=models.IntegerField(choices=[(0, 'Ответить на вопрос'), (1, 'Написать развёрнутый ответ'), (2, 'Отметить верные утверждения'), (3, 'Выбрать одно верное утверждение'), (4, 'Соотнести что-то с чем-то'), (5, 'Составить правильный порядок карточек')], default=0, verbose_name='Тип упражнения'),
        ),
    ]
