# Generated by Django 4.0.2 on 2022-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_keymatchlistexercise_current_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymatchlistexercise',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
