# Generated by Django 4.0.2 on 2022-05-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_projectexercise_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='current_version',
        ),
        migrations.DeleteModel(
            name='TestVersion',
        ),
    ]
