# Generated by Django 4.0.2 on 2022-06-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0036_keymatchlistexercise_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfact',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
    ]
